clockify:
  url: https://api.clockify.me/api/v1/
  token: XXXXXXXXXXXX
  timezone: Europe/Rome
  workspace_name: xxxxx
  hourly_rate: 6000
  currency: EURO

timing:
  url: https://web.timingapp.com/api/v1/
  token: XXXXXXXXXXXX

t2c:
  refresh_time: 10800

telegram:
  token: xxxxxxx
  chat_id: xxxxxxx
